import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  docs: {
    Introduction: [
      "introduction/getting-started",
      "introduction/formatting-options",
      "introduction/inline-styles",
      "introduction/blocks",
      "introduction/entities",
      "introduction/decorators",
      "introduction/arbitrary-controls",
      "introduction/plugins",
    ],
    Guides: [
      "guides/importing-and-exporting-html",
      "guides/form-validation",
      "guides/getting-started-with-extensions",
      "guides/draftjs-vs-draftail",
      "guides/extensions-tutorial-max-length",
      "guides/extensions-tutorial-linkify",
    ],
    "User guides": [
      "user-guides/user-guide",
      "user-guides/keyboard-shortcuts",
      "user-guides/markdown-support",
    ],
    Reference: [
      "reference/api",
      "reference/content-storage",
      "reference/controlled-component",
      "reference/ui-theming",
      "reference/customising-icons",
      "reference/customising-toolbars",
      "reference/i18n",
      "reference/browser-support",
      "reference/troubleshooting",
    ],
    "Draft.js documentation": {
      Quickstart: [
        "draft-js/quickstart/overview",
        "draft-js/quickstart/api-basics",
        "draft-js/quickstart/rich-styling",
      ],
      "Advanced topics": [
        "draft-js/advanced-topics/block-components",
        "draft-js/advanced-topics/block-styling",
        "draft-js/advanced-topics/custom-block-render-map",
        "draft-js/advanced-topics/decorators",
        "draft-js/advanced-topics/editorstate-race-conditions",
        "draft-js/advanced-topics/entities",
        "draft-js/advanced-topics/inline-styles",
        "draft-js/advanced-topics/issues-and-pitfalls",
        "draft-js/advanced-topics/key-bindings",
        "draft-js/advanced-topics/managing-focus",
        "draft-js/advanced-topics/nested-lists",
        "draft-js/advanced-topics/text-direction",
      ],
      "API Reference": [
        "draft-js/api-reference/atomic-block-utils",
        "draft-js/api-reference/character-metadata",
        "draft-js/api-reference/composite-decorator",
        "draft-js/api-reference/content-block",
        "draft-js/api-reference/content-state",
        "draft-js/api-reference/data-conversion",
        "draft-js/api-reference/editor",
        "draft-js/api-reference/editor-change-type",
        "draft-js/api-reference/editor-state",
        "draft-js/api-reference/entity",
        "draft-js/api-reference/key-binding-util",
        "draft-js/api-reference/modifier",
        "draft-js/api-reference/rich-utils",
        "draft-js/api-reference/selection-state",
        "draft-js/api-reference/v0-10-api-migration",
      ],
    },
  },
}

export default sidebars
