name: CI
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: ".node-version"
      - run: npm ci
      # Test Git hooks in CI, to make sure script upgrades do not break them.
      - run: npm run prepare
      # Test commit message validation in CI.
      - run: git log -1 --pretty=%B >> latest.log && ./.git/hooks/commit-msg latest.log
      - uses: biomejs/setup-biome@v2
      - run: biome ci
      - run: npx prettier --check '**/*.{md,yaml,yml,html}'
      - run: npx tsc --noEmit
