name: CI
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".node-version"
      - run: npm ci
      # Test Git hooks in CI, to make sure script upgrades do not break them.
      - run: npm run prepare
      # Test commit message validation in CI.
      - run: git log -1 --pretty=%B >> latest.log && ./.git/hooks/commit-msg latest.log
      - uses: biomejs/setup-biome@4c91541eaada48f67d7dbd7833600ce162b68f51 # v2
      - run: biome ci
      - run: npx prettier --check '**/*.{md,yaml,yml,html}'
      - run: npx tsc --noEmit
