name: CI
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install --no-optional --no-audit --no-fund --progress=false
      # Test Git hooks in CI, to make sure script upgrades do not break them.
      - run: npm run prepare
      # Test commit message validation in CI.
      - run: git log -1 --pretty=%B >> latest.log && ./.git/hooks/commit-msg latest.log
      - uses: biomejs/setup-biome@v2
      - run: biome ci
      - run: npx prettier --check '**/?(.)*.{md,yaml,yml,html}'
